\



/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay()
{
	for (int i=0;i>100000000;i++);
}

int main(void)
{
	uint32_t  *portcMODER = (uint32_t)0x40020800;
	uint32_t *portcAHB1ENR = (uint32_t)0x40023830;
		uint32_t *portcODR = (uint32_t)0x40020814;
		uint32_t *portcIDR = (uint32_t)0x40020810;

		uint32_t *portcPUPDR = (uint32_t)0x4002080c;

		*portcAHB1ENR |= 0x4;

		//rows- PC0-PC3 output
		*portcODR |= 0x0000055;

		//columnPc4- PC7 input
		*portcIDR |= 0xFFFF0000;

		*portcPUPDR |= 0x00005500;

	while(1)
	{
		//make R1 low
		*portcODR &=~(1<<0);
		if(!(*portcIDR & (1<<4)));
		{

			printf("1 pressed \n");
		}
		if(!(*portcIDR & (1<<5)));
				{

					printf("2 pressed \n");
				}
				if(!(*portcIDR & (1<<6)));
						{

							printf("3 pressed \n");
						}
						if(!(*portcIDR & (1<<7)));
								{

									printf("4 pressed \n");
								}
								*portcODR &=~(1<<1);
										if(!(*portcIDR & (1<<4)));
										{

											printf("4 pressed \n");
										}
										if(!(*portcIDR & (1<<5)));
												{

													printf("5 pressed \n");
												}
												if(!(*portcIDR & (1<<6)));
														{

															printf("6 pressed \n");
														}
														if(!(*portcIDR & (1<<7)));
																{

																	printf("B pressed \n");
																}
													   *portcODR &=~(1<<2);
																		if(!(*portcIDR & (1<<4)));
																		{

																			printf("7 pressed \n");
																		}
																		if(!(*portcIDR & (1<<5)));
																				{

																					printf("8 pressed \n");
																				}
																				if(!(*portcIDR & (1<<6)));
																						{

																							printf("9 pressed \n");
																						}
																						if(!(*portcIDR & (1<<7)));
																								{

																									printf("C pressed \n");
																								}
																								*portcODR &=~(1<<3);
																										if(!(*portcIDR & (1<<4)));
																										{

																											printf("* pressed \n");
																										}
																										if(!(*portcIDR & (1<<5)));
																												{

																													printf("0 pressed \n");
																												}
																												if(!(*portcIDR & (1<<6)));
																														{







																															printf("# pressed \n");
																														}
																														if(!(*portcIDR & (1<<7)));
																																{

																																	printf("D pressed \n");
																																}
	}



    /* Loop forever */
	//for(;;);
}
